version: "3.3"

services:
  blog_db:
    image: postgres:latest
    container_name: blog_db
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=final_project
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=18butomu
    ports:
      - "5442:5432"
    restart: always
  blog_web:
    image: blog_web
    build: ./
    container_name: blog_web
    env_file:
      - .env
    entrypoint: ["docker/web.sh"]
    ports:
      - "8010:8000"
    depends_on:
      - blog_db
volumes:
  postgres_db: